Feature:  add acessibilidade4Noobs
he4rt/4noobs pull request #102
Opened 2023-01-24 19:12 UTC by Gabrielbsb21

Bom momento, pessoal. 
Estou abrindo esse pr com o objetivo de adicionar um repositório sobre a temática da acessibilidade digital, mais especificamente sobre acessibilidade na web. Muito se é pensado sobre criar e produzir, mas
pouco se é falado sobre quem os consome e como tornar os softwares
acessíveis para todos.

Acessibilidade na web e um tema que venho estudando bastante (inclusive meu tcc esta sendo feito nessa area) e um dos grandes problemas  para o contínuo problema da inacessibilidade na web é a falta de conhecimento dos desenvolvedores sobre as técnicas de implementação de acessibilidade.

Dessa forma, estou criando esse conteúdo para ajudar no ensino sobre acessibilidade na web e para a gente tornar a web um local de todos e para todos.

Ainda falta um capítulo no repositorio, que irei escrever sobre o WAI-ARIA. 

Qualquer coisa estou a disposição tanto para ajudar no ensino da acessibilidade na web, como para corrigir ou melhorar o repositório.

Obrigado!!

2023-05-19 22:49 UTC, Novout requested changes
Considero que ficaria melhor na seção **Diversos**

2023-05-20 14:18 UTC, Gabrielbsb21 commented
> Considero que ficaria melhor na seção **Diversos**

Tudo bem. Alteração realizada, @Novout 
Muito obrigado pela atenção.

Qualquer coisa estou a disposição.

2023-05-20 18:12 UTC, Novout reviewed
Ok! Quando as seções que faltam estiverem prontas eu faço a review :)

2023-06-15 19:13 UTC, Gabrielbsb21 commented
> Ok! Quando as seções que faltam estiverem prontas eu faço a review :)

Eu finalizei as seções que estavam faltando. Qualquer coisa estou a disposição.

Muito Obrigado!!

2023-06-16 00:49 UTC, Novout commented
Ok! Só peço para corrigir alguns link's de redirecionamento que estão dando 404:

![image](https://github.com/he4rt/4noobs/assets/41403842/4beb53e6-4ae7-494e-8672-b14c8c7e6b47)

2023-06-16 00:50 UTC, Novout approved these changes

2023-06-16 12:28 UTC, Gabrielbsb21 commented
> Ok! Só peço para corrigir alguns link's de redirecionamento que estão dando 404:
> 
> ![image](https://user-images.githubusercontent.com/41403842/246283610-4beb53e6-4ae7-494e-8672-b14c8c7e6b47.png)

Problema solucionado, todos os links estao funcionando.

Muito obrigado pela paciência.

2023-08-15 13:07 UTC, Gabrielbsb21 commented
Oi pessoal, ainda tem algum problema para eu corrigir?
Se tiver, podem falar que estou a disposição.

2023-08-15 22:03 UTC, merged