Update README.MD
he4rt/4noobs pull request #50
Opened 2021-07-09 01:08 UTC by DantasB

Adicionando o Bash4Noobs

2021-07-09 13:07 UTC, jpaulohe4rt approved these changes

2021-07-10 17:35 UTC, kjkGustavo requested changes

2021-07-10 17:35 UTC, kjkGustavo commented on README.MD
> +| Bash | Aprenda a linguagem de script básica do seu sistema UNIX. | [Bruno Dantas de Paiva](https://github.com/DantasB)  | [Clique aqui ➡️](https://github.com/DantasB/Bash4Noobs) |
Se possível adicionar todos os contribuidores do projeto.

2021-07-10 18:18 UTC, DantasB commented on README.MD
> +| Bash | Aprenda a linguagem de script básica do seu sistema UNIX. | [Bruno Dantas de Paiva](https://github.com/DantasB)  | [Clique aqui ➡️](https://github.com/DantasB/Bash4Noobs) |
@kjkGustavo Obrigado por notificar! Como o Gabriel contribuiu para o projeto ao final esqueci de colocar. 

Corrigido!

2021-07-10 19:19 UTC, kjkGustavo approved these changes

2021-07-10 19:19 UTC, merged