Automation4noobs
he4rt/4noobs pull request #54
Opened 2021-08-05 21:38 UTC by andreluispy

Galera apresentando, automation4noobs. Ele trata de automação e já tem conteudo de Testes unitários com UNITTEST, depois vou adicionar conteudos e pra quem quiser ajudar, é só fazer pull :heart:: https://github.com/andreluispy/automation4noobs

Eu coloquei ele dentro da parte que criei: `Conteúdos Diversos`, tava sem ideia então pode mudar o nome kkkk

2021-08-05 21:39 UTC, andreluispy commented
OBS: Criei essa área nova porque não tinha nenhuma que se encaixava com o conteúdo do 4noobs

2021-08-06 11:53 UTC, carlosdnba commented
Na minha humilde opinião acho que faz mais sentido ser renomeado para `tests4noobs`

2021-08-09 21:00 UTC, JVictorV commented
Concordo com o @carlosdnba, parece que o conteúdo ta muito mais relacionado a testes do que a automação

2021-08-10 14:25 UTC, andreluispy commented
Em primeiro lugar, peço desculpas pela demora em responder

Melhor dizendo, o 4noob de automação vai lidar com automação em geral(que envolve testes), até agora ele só tem testes com unittest, mas já estou trabalhando na parte de automação com pyautogui/selenium e também tenho um amigo criando uma parte sobre testes em DJANGO/Angular.

Em breve estarão disponíveis, estou terminando as correções gramaticais para liberar essa parte da automação! O repositório será um aglomerado de informações sobre toda a área de automação, tanto que convido todos a escreverem sobre testes/automação em outras linguagens e frameworks para ajudar desenvolver o conteúdo!

2021-10-06 01:55 UTC, Logikoz requested changes
O conteudo atual não está condizente com o proprosito deste 4noob, entendo a parte que citou sobre estar incompleto, porém para entrar no repositorio principal você precisa entregar oque propôs.

Uma sugestão seria mudar o nome do repositorio para `testes4noobs` como foi citado acima e escrever um pouco mais sobre testes em geral, creio que `automação` não é o nome ideal para esse 4noobs.

2021-12-08 12:40 UTC, closed without merging