Add Postgresql4Noobs to projects list
he4rt/4noobs pull request #69
Opened 2022-04-12 16:35 UTC by RomuloHe4rt

2022-04-29 02:08 UTC, Novout approved these changes

2022-04-29 02:10 UTC, Novout requested changes
Falta inserir no .github/config.json

2022-04-29 02:22 UTC, Novout approved these changes

2022-04-30 00:29 UTC, DanielHe4rt commented
Adicionar tipo de dados SEQUENCE (auto increment) antes de ser aprovado :p

2022-05-04 14:05 UTC, rohlacanna commented
> Adicionar tipo de dados SEQUENCE (auto increment) antes de ser aprovado :p

Prontinho! foi adicionado :')

2022-05-05 01:01 UTC, Novout approved these changes

2022-05-11 15:34 UTC, DanielHe4rt approved these changes

2022-05-11 15:35 UTC, merged