Adição do Django4Noobs
he4rt/4noobs pull request #71
Opened 2022-05-24 07:18 UTC by brunovhk

2022-05-26 20:49 UTC, Novout requested changes
Remover .idea

2022-05-26 20:50 UTC, Novout requested changes
Adicionar curso em `.github/config.json`

2022-05-27 00:07 UTC, Novout approved these changes

2022-06-02 20:31 UTC, epcgrs approved these changes

2022-08-24 17:41 UTC, merged